### ISSUE TITLE
authorize.php generates HTTP code 403

### ISSUE THREAD

**Issue by gdilove** [dravenk/dp#1]
Add below code to site.conf in line 30:
![image](https://user-images.githubusercontent.com/2673699/161437291-a40f57e3-08f5-4a78-9cd2-ce3407b2c533.png)

    ## authorize.php generates HTTP code 403
    ## https://www.drupal.org/forum/support/post-installation/2016-08-07/authorizephp-generates-http-code-403
    rewrite ^/core/authorize.php/core/authorize.php(.*)$ /core/authorize.php$1;

**Comment by dravenk** [comment]
The problem cannot be reproduced because a replay step is not provided.
The link provides a solution that you can modify `settings.php` in your project to solve your problem or customize the `site.conf` by mounting it to your container.
>     $settings['allow_authorize_operations'] = FALSE; #set it to True
